import type { PluginOption, ResolvedConfig } from 'vite';

/**
 * @description
 * Vite plugin that normalizes asset URLs when a non-root `base`
 * path is used during production builds.
 *
 * When Vite builds an application with a custom `base` option,
 * it automatically prefixes all `href` and `src` attributes in
 * `index.html` with that base path.
 *
 * This behavior breaks applications that must run both:
 * - as a standalone app, and
 * - when embedded inside another host application.
 *
 * This plugin:
 * 1. Removes the injected base prefix from asset URLs.
 * 2. Injects a `<base>` tag into the HTML `<head>` instead.
 *
 * Using a `<base>` tag keeps relative asset resolution working
 * while allowing the application to be mounted under any path.
 *
 * Applied only during the production build.
 */
export function viteBasePathHtmlPlugin(): PluginOption {
	let resolvedConfig: ResolvedConfig;
	return {
		name: 'matjar:base-path-html',
		configResolved(config) {
			resolvedConfig = config;
		},
		apply: 'build',
		transformIndexHtml(html, ctx) {
			// Ignore HTML files generated by tools like Storybook
			if (
				ctx.filename &&
				(ctx.filename.includes('iframe.html') || ctx.filename.includes('storybook'))
			) {
				return html;
			}

			const base = resolvedConfig.base;

			// Nothing to do when using root base
			if (!base || base === '/') {
				return html;
			}

			const normalizedBase = base.replace(/\/$/, '');

			/**
			 * Remove Vite-injected base prefix from asset attributes.
			 * Handles both:
			 *   href="/base/..."
			 *   src="/base/..."
			 */
			const attributeRegex = new RegExp(`(href|src)=(["'])${normalizedBase}/?`, 'g');

			let transformedHtml = html.replace(attributeRegex, '$1=$2');

			// Inject <base> tag so browser resolves assets correctly
			const baseTag = `    <base href="${base}">\n`;

			transformedHtml = transformedHtml.replace(/<head>/i, `<head>\n${baseTag}`);
			return transformedHtml;
		},
	};
}
