
            // biome-ignore-all lint: generated-content
            // biome-ignore-all format: generated-content
        
/** This file was generated by the "codegen" npm script. */

export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

export class ApiError {
  readonly __typename: string;
  readonly code: string;
  readonly message: Scalars['String'];
}

export class InvalidCredentialsError extends ApiError {
  readonly __typename = 'InvalidCredentialsError';
  readonly code = 'INVALID_CREDENTIALS_ERROR' as any;
  readonly message = 'INVALID_CREDENTIALS_ERROR';
  readonly authenticationError: Scalars['String'];
  constructor(
    input: { authenticationError: Scalars['String'] }
  ) {
    super();
    this.authenticationError = input.authenticationError
  }
}


const errorTypeNames = new Set<string>(['InvalidCredentialsError']);
function isGraphQLApiError(input: any): input is import('@matjar/common/lib/generated-types').ApiError {
  return input instanceof ApiError || errorTypeNames.has(input.__typename);
}

export const adminErrorOperationTypeResolvers = {
  AuthenticateAdminUserResult: {
    __resolveType(value: any) {
      return isGraphQLApiError(value) ? (value as any).__typename : 'AuthenticatedUser';
    },
  },
};