
            // biome-ignore-all lint: generated-content
            // biome-ignore-all format: generated-content
        
/** This file was generated by the "codegen" npm script. */

export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  DateTime: any;
  JSON: any;
  Upload: any;
};

export class ApiError {
  readonly __typename: string;
  readonly errorCode: string;
  readonly message: Scalars['String'];
}

export class InvalidCredentialsError extends ApiError {
  readonly __typename = 'InvalidCredentialsError';
  readonly errorCode = 'INVALID_CREDENTIALS_ERROR' as any;
  readonly message = 'INVALID_CREDENTIALS_ERROR';
  readonly authenticationError: Scalars['String'];
  constructor(
    input: { authenticationError: Scalars['String'] }
  ) {
    super();
    this.authenticationError = input.authenticationError
  }
}

export class InvalidMimetypeError extends ApiError {
  readonly __typename = 'InvalidMimetypeError';
  readonly errorCode = 'INVALID_MIMETYPE_ERROR' as any;
  readonly message = 'INVALID_MIMETYPE_ERROR';
  readonly fileName: Scalars['String'];
  readonly mimeType: Scalars['String'];
  constructor(
    input: { fileName: Scalars['String'], mimeType: Scalars['String'] }
  ) {
    super();
    this.fileName = input.fileName
    this.mimeType = input.mimeType
  }
}

export class RoleCodeConflictError extends ApiError {
  readonly __typename = 'RoleCodeConflictError';
  readonly errorCode = 'ROLE_CODE_CONFLICT_ERROR' as any;
  readonly message = 'ROLE_CODE_CONFLICT_ERROR';
  constructor(

  ) {
    super();
  }
}


const errorTypeNames = new Set<string>(['InvalidCredentialsError', 'InvalidMimetypeError', 'RoleCodeConflictError']);
function isGraphQLApiError(input: any): input is import('@matjar/common/lib/generated-types').ApiError {
  return input instanceof ApiError || errorTypeNames.has(input.__typename);
}

export const adminErrorOperationTypeResolvers = {
  AuthenticateAdminUserResult: {
    __resolveType(value: any) {
      return isGraphQLApiError(value) ? (value as any).__typename : 'AuthenticatedAdminUser';
    },
  },
  CreateAssetsResult: {
    __resolveType(value: any) {
      return isGraphQLApiError(value) ? (value as any).__typename : 'Asset';
    },
  },
  CreateRoleResult: {
    __resolveType(value: any) {
      return isGraphQLApiError(value) ? (value as any).__typename : 'Role';
    },
  },
  UpdateRoleResult: {
    __resolveType(value: any) {
      return isGraphQLApiError(value) ? (value as any).__typename : 'Role';
    },
  },
};