import Stream from 'node:stream';
import { LifecycleStrategy } from '../../../common/types/lifecycle-strategy';

export interface AssetStorageStrategy extends LifecycleStrategy {
	/**
	 * @description
	 * Saves a file from a readable stream and return a unique identifier of that file.
	 *
	 * :::info
	 * Unique identifier could be a URL or an ID
	 * :::
	 */
	saveFileFromStream(
		stream: Stream,
		fileInfo: {
			filename: string;
			mimetype?: string;
		},
	): Promise<string>;

	/**
	 * @description
	 * Saves a file from buffer and return a unique identifier of that file.
	 *
	 * ::info
	 * Unique identifier could be a URL or an ID
	 * :::
	 */
	saveFileFromBuffer(
		buffer: Buffer,
		fileInfo: {
			filename: string;
			mimetype?: string;
		},
	): Promise<string>;

	/**
	 * @description
	 * Reads a file by its unique identifier which was generated by the saveFile methods
	 * and returns the file as a Stream
	 */
	readFileToStream(identifier: string): Promise<Stream>;

	/**
	 * @description
	 * Reads a file by its unique identifier which was generated by the saveFile methods
	 * and returns the file as a Buffer
	 */
	readFileToBuffer(identifier: string): Promise<Buffer>;

	deleteFile(identifier: string): Promise<void>;

	/**
	 * @description
	 * Checks whether a file with the given name already exists
	 */
	fileExists(filename: string): Promise<boolean>;

	/**
	 * @description
	 * Transforms the identifier generated by the saveFile methods into
	 * an absolute URL if it's not already in this form.
	 *
	 * :::info
	 * if the identifier is already an absolute URL, this method becomes optional
	 * :::
	 */
	toAbsoluteUrl?(request: Request, identifier: string): string;
}
