/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAssetsAssetsRouteImport } from './routes/_authenticated/_assets/assets'
import { Route as AuthenticatedAdministratorsAdministratorsRouteImport } from './routes/_authenticated/_administrators/administrators'
import { Route as AuthenticatedAssetsAssetsIdRouteImport } from './routes/_authenticated/_assets/assets_.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssetsAssetsRoute =
  AuthenticatedAssetsAssetsRouteImport.update({
    id: '/_assets/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministratorsAdministratorsRoute =
  AuthenticatedAdministratorsAdministratorsRouteImport.update({
    id: '/_administrators/administrators',
    path: '/administrators',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsAssetsIdRoute =
  AuthenticatedAssetsAssetsIdRouteImport.update({
    id: '/_assets/assets_/$id',
    path: '/assets/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/administrators': typeof AuthenticatedAdministratorsAdministratorsRoute
  '/assets': typeof AuthenticatedAssetsAssetsRoute
  '/assets/$id': typeof AuthenticatedAssetsAssetsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/administrators': typeof AuthenticatedAdministratorsAdministratorsRoute
  '/assets': typeof AuthenticatedAssetsAssetsRoute
  '/assets/$id': typeof AuthenticatedAssetsAssetsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_administrators/administrators': typeof AuthenticatedAdministratorsAdministratorsRoute
  '/_authenticated/_assets/assets': typeof AuthenticatedAssetsAssetsRoute
  '/_authenticated/_assets/assets_/$id': typeof AuthenticatedAssetsAssetsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/administrators' | '/assets' | '/assets/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/administrators' | '/assets' | '/assets/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/_administrators/administrators'
    | '/_authenticated/_assets/assets'
    | '/_authenticated/_assets/assets_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_assets/assets': {
      id: '/_authenticated/_assets/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsAssetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_administrators/administrators': {
      id: '/_authenticated/_administrators/administrators'
      path: '/administrators'
      fullPath: '/administrators'
      preLoaderRoute: typeof AuthenticatedAdministratorsAdministratorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_assets/assets_/$id': {
      id: '/_authenticated/_assets/assets_/$id'
      path: '/assets/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AuthenticatedAssetsAssetsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdministratorsAdministratorsRoute: typeof AuthenticatedAdministratorsAdministratorsRoute
  AuthenticatedAssetsAssetsRoute: typeof AuthenticatedAssetsAssetsRoute
  AuthenticatedAssetsAssetsIdRoute: typeof AuthenticatedAssetsAssetsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdministratorsAdministratorsRoute:
    AuthenticatedAdministratorsAdministratorsRoute,
  AuthenticatedAssetsAssetsRoute: AuthenticatedAssetsAssetsRoute,
  AuthenticatedAssetsAssetsIdRoute: AuthenticatedAssetsAssetsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
