export const REQUEST_CONTEXT_KEY = Symbol('REQUEST_CONTEXT');
export const REQUEST_CONTEXT_MAP_KEY = Symbol('REQUEST_CONTEXT_MAP');
export const TRANSACTION_MANAGER_KEY = Symbol('TRANSACTION_MANAGER');
export const TRANSACTION_MODE_METADATA_KEY = Symbol('TRANSACTION_MODE');
export const TRANSACTION_ISOLATION_LEVEL_METADATA_KEY = Symbol('TRANSACTION_ISOLATION_LEVEL');
