/** biome-ignore-all lint/suspicious/noExplicitAny: this context is not a runtime context*/

//######################
//# CREDIT: Vendure
//######################

import type { Types } from "@graphql-codegen/plugin-helpers";
import { buildScalars } from "@graphql-codegen/visitor-plugin-common";
import {
	type ASTNode,
	type ASTVisitFn,
	type GraphQLFieldMap,
	type GraphQLNamedType,
	type GraphQLObjectType,
	type GraphQLSchema,
	type GraphQLType,
	type GraphQLUnionType,
	getNamedType,
	isObjectType,
	isUnionType,
	Kind,
	type ObjectTypeDefinitionNode,
	parse,
	printSchema,
	visit,
} from "graphql";

export const ERROR_INTERFACE_NAME = "ApiError";
type TransformedField = {
	name: string;
	type: string;
};

module.exports = {
	plugin: createPlugin,
};

function createPlugin(schema: GraphQLSchema, _document: Types.DocumentFile[], config: any) {
	const printedSchema = printSchema(schema);
	const astNode = parse(printedSchema);
	const result = visit(astNode, {
		leave: errorsVisitor,
	});
	const defs = result.definitions
		.filter((d) => !!d)
		// Ensure the ApiError base class is first
		.sort((a) => ((a as any).includes("class ApiError") ? -1 : 1));

	return {
		content: [
			`/** This file was generated by the "codegen" npm script. */`,
			generateScalars(schema, config),
			...defs,
			defs.length ? generateIsErrorFunction(schema) : "",
			generateTypeResolvers(schema),
		].join("\n\n"),
	};
}

const errorsVisitor: ASTVisitFn<ASTNode> = (node, _key, _parent) => {
	switch (node.kind) {
		case Kind.NON_NULL_TYPE: {
			return node.type.kind === "NamedType"
				? node.type.name.value
				: node.type.kind === "ListType"
					? node.type
					: "";
		}
		case Kind.FIELD_DEFINITION: {
			const type = (node.type.kind === "ListType" ? node.type.type : node.type) as unknown as string;
			const tsType = isScalar(type) ? `Scalars['${type}']` : "any";
			const listPart = node.type.kind === "ListType" ? `[]` : ``;
			return {
				name: node.name.value,
				type: `${tsType}${listPart}`,
			};
		}
		case Kind.SCALAR_TYPE_DEFINITION: {
			return "";
		}
		case Kind.INPUT_OBJECT_TYPE_DEFINITION: {
			return "";
		}
		case Kind.ENUM_TYPE_DEFINITION: {
			return "";
		}
		case Kind.UNION_TYPE_DEFINITION: {
			return "";
		}
		case Kind.INTERFACE_TYPE_DEFINITION: {
			if (node.name.value !== ERROR_INTERFACE_NAME) {
				return "";
			}
			return [
				`export class ${ERROR_INTERFACE_NAME} {`,
				`  readonly __typename: string;`,
				`  readonly errorCode: string;`,
				...(node.fields
					?.filter((f) => (f as any as TransformedField).name !== "errorCode")
					.map((f) => `  readonly ${f.name}: ${f.type};`) ?? []),
				`}`,
			].join("\n");
		}
		case Kind.OBJECT_TYPE_DEFINITION: {
			if (!inheritsFromApiError(node)) {
				return "";
			}
			const constructorArgs = (node.fields as any as TransformedField[]).filter(
				(f) => f.name !== "errorCode" && f.name !== "message",
			);

			return [
				`export class ${node.name.value} extends ${ERROR_INTERFACE_NAME} {`,
				`  readonly __typename = '${node.name.value}';`,
				// We cast this to "any" otherwise we need to specify it as type "ErrorCode",
				// which means shared ErrorResult classes e.g. OrderStateTransitionError
				// will not be compatible between the admin and shop variations.
				`  readonly errorCode = '${camelToUpperSnakeCase(node.name.value)}' as any;`,
				`  readonly message = '${camelToUpperSnakeCase(node.name.value)}';`,
				...constructorArgs.map((f) => `  readonly ${f.name}: ${f.type};`),
				`  constructor(`,
				constructorArgs.length
					? `    input: { ${constructorArgs.map((f) => `${f.name}: ${f.type}`).join(", ")} }`
					: "",
				`  ) {`,
				`    super();`,
				...(constructorArgs.length
					? constructorArgs.map((f) => `    this.${f.name} = input.${f.name}`)
					: []),
				`  }`,
				`}`,
			].join("\n");
		}
	}
};

function generateScalars(schema: GraphQLSchema, config: any) {
	const scalarMap = buildScalars(schema, config.scalars);
	const allScalars = Object.keys(scalarMap)
		.map((scalarName) => {
			const scalarValue = scalarMap[scalarName].output.type;
			return `  ${scalarName}: ${scalarValue};`;
		})
		.join("\n");
	return `export type Scalars = {\n${allScalars}\n};`;
}

function generateIsErrorFunction(schema: GraphQLSchema) {
	const errorNodes = Object.values(schema.getTypeMap())
		.filter(isObjectType)
		.filter((node) => inheritsFromApiError(node));
	return `
const errorTypeNames = new Set<string>([${errorNodes.map((n) => `'${n.name}'`).join(", ")}]);
function isGraphQLApiError(input: any): input is import('@matjar/common/lib/generated-types').${ERROR_INTERFACE_NAME} {
  return input instanceof ${ERROR_INTERFACE_NAME} || errorTypeNames.has(input.__typename);
}`;
}

function generateTypeResolvers(schema: GraphQLSchema) {
	const mutations = getOperationsThatReturnErrorUnions(schema, schema.getMutationType()?.getFields());
	const queries = getOperationsThatReturnErrorUnions(schema, schema.getQueryType()?.getFields());
	const operations = [
		...mutations,
		...queries,
	];
	const varName = isAdminApi(schema)
		? `adminErrorOperationTypeResolvers`
		: `storeErrorOperationTypeResolvers`;
	const result = [
		`export const ${varName} = {`,
	];
	const typesHandled = new Set<string>();
	for (const operation of operations) {
		const returnType = unwrapType(operation.type) as GraphQLUnionType;
		if (!typesHandled.has(returnType.name)) {
			typesHandled.add(returnType.name);
			const nonErrorResult = returnType.getTypes().find((t) => !inheritsFromApiError(t));
			if (!nonErrorResult) {
				throw new Error(
					`The type "${returnType.name}" seems to be a union of only ApiError types. ` +
						`This is not a valid union, as it should also contain a non-error result type.`,
				);
			}
			result.push(
				`  ${returnType.name}: {`,
				`    __resolveType(value: any) {`,
				`      return isGraphQLApiError(value) ? (value as any).__typename : '${nonErrorResult.name}';`,
				`    },`,
				`  },`,
			);
		}
	}
	result.push(`};`);
	return result.join("\n");
}

function getOperationsThatReturnErrorUnions(schema: GraphQLSchema, fields: GraphQLFieldMap<any, any> = {}) {
	return Object.values(fields).filter((operation) => {
		const innerType = unwrapType(operation.type);
		if (isUnionType(innerType)) {
			return isUnionOfResultAndErrors(schema, innerType.getTypes());
		}
		return false;
	});
}

function isUnionOfResultAndErrors(_schema: GraphQLSchema, types: readonly GraphQLObjectType[]) {
	const errorResultTypes = types.filter((type) => {
		if (isObjectType(type)) {
			if (inheritsFromApiError(type)) {
				return true;
			}
		}
		return false;
	});
	return errorResultTypes.length === types.length - 1;
}

function isScalar(type: string): boolean {
	return [
		"ID",
		"String",
		"Boolean",
		"Int",
		"Float",
		"JSON",
		"DateTime",
		"Upload",
	].includes(type);
}

function inheritsFromApiError(node: ObjectTypeDefinitionNode | GraphQLObjectType): boolean {
	const interfaceNames = isObjectType(node)
		? node.getInterfaces().map((i) => i.name)
		: node.interfaces?.map((i) => i.name.value);
	return interfaceNames?.includes(ERROR_INTERFACE_NAME) ?? false;
}

function camelToUpperSnakeCase(input: string): string {
	return input.replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase();
}

function isAdminApi(schema: GraphQLSchema): boolean {
	return !!schema.getType("UpdateGlobalSettingsInput");
}

function unwrapType(type: GraphQLType): GraphQLNamedType {
	return getNamedType(type);
}
